// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt4zP7aCUIwzvXsenrF3fBruD9Q75PbVc',
    appId: '1:769015092321:web:5140eba66189636dd1c620',
    messagingSenderId: '769015092321',
    projectId: 'alemeno-assignment-7fbc5',
    authDomain: 'alemeno-assignment-7fbc5.firebaseapp.com',
    storageBucket: 'alemeno-assignment-7fbc5.appspot.com',
    measurementId: 'G-FVVD75W8XC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn_moRN4pBUWnrzzupQ-nOqqn9OLVnla0',
    appId: '1:769015092321:android:d289dafd45b3c142d1c620',
    messagingSenderId: '769015092321',
    projectId: 'alemeno-assignment-7fbc5',
    storageBucket: 'alemeno-assignment-7fbc5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1ACefWkOfhJFIkFiWRNPPY1EID1e9iEw',
    appId: '1:769015092321:ios:d441d2584f1b677fd1c620',
    messagingSenderId: '769015092321',
    projectId: 'alemeno-assignment-7fbc5',
    storageBucket: 'alemeno-assignment-7fbc5.appspot.com',
    iosClientId: '769015092321-9v9a890bai7ittv97pqqqd9ujk2qb6jn.apps.googleusercontent.com',
    iosBundleId: 'com.example.amlemenoAssignmentTestHimanshuAgrawal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1ACefWkOfhJFIkFiWRNPPY1EID1e9iEw',
    appId: '1:769015092321:ios:b347ecfc6fb2902ad1c620',
    messagingSenderId: '769015092321',
    projectId: 'alemeno-assignment-7fbc5',
    storageBucket: 'alemeno-assignment-7fbc5.appspot.com',
    iosClientId: '769015092321-3c456k6dgsi6iskfdg30l21aneucf03t.apps.googleusercontent.com',
    iosBundleId: 'com.example.amlemenoAssignmentTestHimanshuAgrawal.RunnerTests',
  );
}
